In [2]:
import pandas as pd

In [9]:
df = pd.read_csv('events.csv')

In [10]:
df

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session
0,2020-09-24 11:57:06 UTC,view,1996170,2144415922528452715,electronics.telephone,NaN,31.90,1515915625519388267,LJuJVLEjPT
1,2020-09-24 11:57:26 UTC,view,139905,2144415926932472027,computers.components.cooler,zalman,17.16,1515915625519380411,tdicluNnRY
2,2020-09-24 11:57:27 UTC,view,215454,2144415927158964449,NaN,NaN,9.81,1515915625513238515,4TMArHtXQy
3,2020-09-24 11:57:33 UTC,view,635807,2144415923107266682,computers.peripherals.printer,pantum,113.81,1515915625519014356,aGFYrNgC08
4,2020-09-24 11:57:36 UTC,view,3658723,2144415921169498184,NaN,cameronsino,15.87,1515915625510743344,aa4mmk0kwQ
...,...,...,...,...,...,...,...,...,...
885124,2021-02-28 23:55:01 UTC,view,953226,2144415927553229037,NaN,NaN,219.94,1515915625611023730,FRLqIttxKU
885125,2021-02-28 23:58:05 UTC,view,1715907,2144415927049912542,electronics.video.tv,starwind,80.03,1515915625611024014,g6WqPf50Ma
885126,2021-02-28 23:58:09 UTC,view,4170534,2144415939364389423,electronics.clocks,amazfit,64.92,1515915625611024020,xNIJBqZdkd
885127,2021-02-28 23:58:14 UTC,view,888273,2144415921932861531,electronics.telephone,NaN,10.16,1515915625611024030,9pCbKMIcSx
885128,2021-02-28 23:59:09 UTC,view,743182,2144415935631458761,construction.tools.soldering,kada,65.08,1515915625556087775,BejOXRngEW

In [14]:
df['category_code'].fillna('no_category', inplace=True)
df['brand'].fillna('no_brand', inplace=True)
df

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session
0,2020-09-24 11:57:06 UTC,view,1996170,2144415922528452715,electronics.telephone,no_brand,31.90,1515915625519388267,LJuJVLEjPT
1,2020-09-24 11:57:26 UTC,view,139905,2144415926932472027,computers.components.cooler,zalman,17.16,1515915625519380411,tdicluNnRY
2,2020-09-24 11:57:27 UTC,view,215454,2144415927158964449,no_category,no_brand,9.81,1515915625513238515,4TMArHtXQy
3,2020-09-24 11:57:33 UTC,view,635807,2144415923107266682,computers.peripherals.printer,pantum,113.81,1515915625519014356,aGFYrNgC08
4,2020-09-24 11:57:36 UTC,view,3658723,2144415921169498184,no_category,cameronsino,15.87,1515915625510743344,aa4mmk0kwQ
...,...,...,...,...,...,...,...,...,...
885124,2021-02-28 23:55:01 UTC,view,953226,2144415927553229037,no_category,no_brand,219.94,1515915625611023730,FRLqIttxKU
885125,2021-02-28 23:58:05 UTC,view,1715907,2144415927049912542,electronics.video.tv,starwind,80.03,1515915625611024014,g6WqPf50Ma
885126,2021-02-28 23:58:09 UTC,view,4170534,2144415939364389423,electronics.clocks,amazfit,64.92,1515915625611024020,xNIJBqZdkd
885127,2021-02-28 23:58:14 UTC,view,888273,2144415921932861531,electronics.telephone,no_brand,10.16,1515915625611024030,9pCbKMIcSx
885128,2021-02-28 23:59:09 UTC,view,743182,2144415935631458761,construction.tools.soldering,kada,65.08,1515915625556087775,BejOXRngEW

In [16]:
total_rows = len(df)
no_category_count = df['category_code'].value_counts().get('no_category', 0)
percentage_no_category = (no_category_count / total_rows) * 100

# Calculate the percentage of 'no_brand' values
total_rows = len(df)
no_brand_count = df['brand'].value_counts().get('no_brand', 0)
percentage_no_brand = (no_brand_count / total_rows) * 100

print(f"Percentage of 'no_category' values: {percentage_no_category:.2f}%")
print(f"Percentage of 'no_brand' values: {percentage_no_brand:.2f}%")

Percentage of 'no_category' values: 26.69%
Percentage of 'no_brand' values: 23.99%

In [18]:
# VÃ©rifier si la colonne 'event_time' contient des valeurs nulles
print(df['event_time'].isnull().sum())

# Remplacer les valeurs nulles par une chaÃ®ne vide pour Ã©viter les erreurs lors de la sÃ©paration
df['event_time'].fillna('', inplace=True)

# SÃ©parer la colonne 'event_time' en deux colonnes 'date' et 'heures'
df['date'] = df['event_time'].str.split(' ', expand=True)[0]
df['heures'] = df['event_time'].str.split(' ', expand=True)[1]

# Supprimer le fuseau horaire 'UTC' de la colonne 'heures' si nÃ©cessaire
df['heures'] = df['heures'].str.replace(' UTC', '')

# Optionnel: Supprimer la colonne 'event_time' originale
# df.drop(columns=['event_time'], inplace=True)

0

In [19]:
df

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session,date,heures
0,2020-09-24 11:57:06 UTC,view,1996170,2144415922528452715,electronics.telephone,no_brand,31.90,1515915625519388267,LJuJVLEjPT,2020-09-24,11:57:06
1,2020-09-24 11:57:26 UTC,view,139905,2144415926932472027,computers.components.cooler,zalman,17.16,1515915625519380411,tdicluNnRY,2020-09-24,11:57:26
2,2020-09-24 11:57:27 UTC,view,215454,2144415927158964449,no_category,no_brand,9.81,1515915625513238515,4TMArHtXQy,2020-09-24,11:57:27
3,2020-09-24 11:57:33 UTC,view,635807,2144415923107266682,computers.peripherals.printer,pantum,113.81,1515915625519014356,aGFYrNgC08,2020-09-24,11:57:33
4,2020-09-24 11:57:36 UTC,view,3658723,2144415921169498184,no_category,cameronsino,15.87,1515915625510743344,aa4mmk0kwQ,2020-09-24,11:57:36
...,...,...,...,...,...,...,...,...,...,...,...
885124,2021-02-28 23:55:01 UTC,view,953226,2144415927553229037,no_category,no_brand,219.94,1515915625611023730,FRLqIttxKU,2021-02-28,23:55:01
885125,2021-02-28 23:58:05 UTC,view,1715907,2144415927049912542,electronics.video.tv,starwind,80.03,1515915625611024014,g6WqPf50Ma,2021-02-28,23:58:05
885126,2021-02-28 23:58:09 UTC,view,4170534,2144415939364389423,electronics.clocks,amazfit,64.92,1515915625611024020,xNIJBqZdkd,2021-02-28,23:58:09
885127,2021-02-28 23:58:14 UTC,view,888273,2144415921932861531,electronics.telephone,no_brand,10.16,1515915625611024030,9pCbKMIcSx,2021-02-28,23:58:14
885128,2021-02-28 23:59:09 UTC,view,743182,2144415935631458761,construction.tools.soldering,kada,65.08,1515915625556087775,BejOXRngEW,2021-02-28,23:59:09

In [20]:
df.head()

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session,date,heures
0,2020-09-24 11:57:06 UTC,view,1996170,2144415922528452715,electronics.telephone,no_brand,31.90,1515915625519388267,LJuJVLEjPT,2020-09-24,11:57:06
1,2020-09-24 11:57:26 UTC,view,139905,2144415926932472027,computers.components.cooler,zalman,17.16,1515915625519380411,tdicluNnRY,2020-09-24,11:57:26
2,2020-09-24 11:57:27 UTC,view,215454,2144415927158964449,no_category,no_brand,9.81,1515915625513238515,4TMArHtXQy,2020-09-24,11:57:27
3,2020-09-24 11:57:33 UTC,view,635807,2144415923107266682,computers.peripherals.printer,pantum,113.81,1515915625519014356,aGFYrNgC08,2020-09-24,11:57:33
4,2020-09-24 11:57:36 UTC,view,3658723,2144415921169498184,no_category,cameronsino,15.87,1515915625510743344,aa4mmk0kwQ,2020-09-24,11:57:36